# Generated by Django 3.0.2 on 2020-01-19 11:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('template', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=30)),
                ('end_dt', models.DateTimeField(verbose_name='DT to end display of this screen')),
                ('start_dt', models.DateTimeField(verbose_name='DT to start display this screen')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gui.Template')),
            ],
        ),
    ]
