# Generated by Django 3.0.2 on 2020-01-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gui', '0004_auto_20200119_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='note',
            field=models.TextField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.TextField(
                default='{\n    "text": {\n        "textString": "PixOn",\n        "scrollText": "auto", \n        "scrollTextDelay": 20,\n        "position": {\n            "x": 8,\n            "y": 1\n        },\n        "color": {\n            "r": 255, \n            "g": 255, \n            "b": 255    \n        }\n    }\n}',
                max_length=3072),
        ),
    ]
