# Generated by Django 3.0.2 on 2020-01-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0005_auto_20200119_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
