# Generated by Django 3.0.2 on 2020-01-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0006_bitmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitmap',
            name='json',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='template',
            field=models.TextField(default='{\n    "text": {\n        "textString": "PixOn",\n        "scrollText": "auto", \n        "scrollTextDelay": 20,\n        "position": {\n            "x": 8,\n            "y": 1\n        }\n    }\n}', max_length=3072),
        ),
    ]
