# Generated by Django 3.0.2 on 2020-01-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gui', '0007_auto_20200119_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitmap',
            name='json',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
